// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHxttw6KGFizNiMVhlvAR0xG-5TbAgN8',
    appId: '1:667029338646:web:b149367bd21d9599f31337',
    messagingSenderId: '667029338646',
    projectId: 'mata3mna-43574',
    authDomain: 'mata3mna-43574.firebaseapp.com',
    storageBucket: 'mata3mna-43574.firebasestorage.app',
    measurementId: 'G-XR1QRHGZJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmtirn-AkibuZrey6yWclb7TUDhSG71NI',
    appId: '1:667029338646:android:3c37665e497ecb4cf31337',
    messagingSenderId: '667029338646',
    projectId: 'mata3mna-43574',
    storageBucket: 'mata3mna-43574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKoOwxKRtMzi5vxQcVmgI8clPYivVDd0',
    appId: '1:667029338646:ios:9d5318a347cbf221f31337',
    messagingSenderId: '667029338646',
    projectId: 'mata3mna-43574',
    storageBucket: 'mata3mna-43574.firebasestorage.app',
    androidClientId: '667029338646-ppf6q7tkmvss5snecj6f9u8i130htc8d.apps.googleusercontent.com',
    iosClientId: '667029338646-0mt8otj92973n9ko2gugjvq2gt8afivq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mata3mna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKoOwxKRtMzi5vxQcVmgI8clPYivVDd0',
    appId: '1:667029338646:ios:9d5318a347cbf221f31337',
    messagingSenderId: '667029338646',
    projectId: 'mata3mna-43574',
    storageBucket: 'mata3mna-43574.firebasestorage.app',
    androidClientId: '667029338646-ppf6q7tkmvss5snecj6f9u8i130htc8d.apps.googleusercontent.com',
    iosClientId: '667029338646-0mt8otj92973n9ko2gugjvq2gt8afivq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mata3mna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsHxttw6KGFizNiMVhlvAR0xG-5TbAgN8',
    appId: '1:667029338646:web:486d6cc38cde18aaf31337',
    messagingSenderId: '667029338646',
    projectId: 'mata3mna-43574',
    authDomain: 'mata3mna-43574.firebaseapp.com',
    storageBucket: 'mata3mna-43574.firebasestorage.app',
    measurementId: 'G-WW29L7BCFQ',
  );
}
